---
apiVersion: v1
kind: Pod
metadata:
  name: 1-c-ubuntu-os

spec:
  containers:
  - name: 1-c-ubuntu-os
    image: ubuntu
    command: ["/bin/bash", "-c", "while true ; do echo hello all ; sleep 5; done"]
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"

