echo 

'---
apiVersion: v1
kind: Pod
metadata:
  name: 1-c-ubuntu-os

spec:
  containers:
  - name: 2-c-annotation
    image: ubuntu
    command: ["/bin/bash" ,"-c", "while true ; do echo c02_annotation.yaml ; sleep 5; done"]
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
