---
apiVersion: v1
kind: Pod
metadata:
  name: 2-c-annotation
  annotations:
    description: pod creation to test the annoatation-comments on pod

spec:
  containers:
  - name: 2-c-annotation
    image: ubuntu
    command: ["/bin/bash" ,"-c", "while true ; do echo c02_annotation.yaml ; sleep 5; done"]
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
