---
apiVersion: v1
kind: Pod
metadata:
  name: testpod-co1

spec:
  containers:
  - name: testpod-co1
    image: ubuntu
    command: ["/bin/bash", "-c", "while true ; do echo hello all ; sleep 5; done"]
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
